[package]
name = "asphalt"
version = "0.1.1"
edition = "2021"

[dependencies]
blake3 = "1.5.0"
clap = { version = "4.5.1", features = ["derive"] }
console = { version = "0.15.8", features = ["ansi-parsing"] }
dotenv = "0.15.0"
log = "0.4.21"
rbxcloud = "0.6.1"
reqwest = { version = "0.11.24", features = ["gzip"] }
serde = { version = "1.0.197", features = ["derive"] }
serde-xml-rs = "0.6.0"
tokio = { version = "1.36.0" }
toml = "0.8.10"
