name: Release

on:
    push:
        tags: ["*"]
    workflow_dispatch:

jobs:
    windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Build release binary
              run: cargo build --verbose --locked --release

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: asphalt-win64
                  path: target/release/asphalt.exe

    macos:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

            - name: Build release binary
              run: |
                  source $HOME/.cargo/env
                  cargo build --verbose --locked --release

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: asphalt-macos
                  path: target/release/asphalt

    linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Build
              run: cargo build --locked --verbose --release
              env:
                  OPENSSL_STATIC: 1

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: asphalt-linux
                  path: target/release/asphalt
